[package]
name = "naturalneighbor"
version = "1.0.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"delaunator" = "1.0.2"
"rstar" = "0.11.0"

[dev-dependencies]
"image" = "0.24.7"
"rand" = "0.8.4"
